# Generated by Django 5.0.6 on 2024-05-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0001_initial'),
        ('Borrower', '0001_initial'),
        ('Branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('status', models.CharField(choices=[(0, 'ON_LOAN'), (1, 'RETURNED'), (2, 'OVERDUE')], max_length=20)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book')),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Borrower.borrower')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branch.branch')),
            ],
        ),
    ]
