# Generated by Django 5.0.6 on 2024-05-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Author', '0001_initial'),
        ('Branch', '0001_initial'),
        ('Category', '0001_initial'),
        ('Publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('summery', models.CharField(blank=True, max_length=500, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.author')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branch.branch')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publisher.publisher')),
            ],
        ),
    ]
